### ISSUE TITLE
move file request 

### ISSUE THREAD

**Issue by lesliejelliott** [icewind1991/files_notify_redis#2]
the move json is formatted as suggested but the closure fails each time, as you can see it expects a Change not a RenameChange  

An unhandled exception has been thrown:
TypeError: Argument 1 passed to OCA\FilesNotifyRedis\Command\NotifyCommand::OCA\FilesNotifyRedis\Command\{closure}() must be an instance of OCA\FilesNotifyRedis\Change\Change, instance of OCA\FilesNotifyRedis\Change\RenameChange given, called in /var/www/nextcloud/apps/files_notify_redis/lib/Notify/NotifyHandler.php on line 170 and defined in /var/www/nextcloud/apps/files_notify_redis/lib/Command/NotifyCommand.php:108
Stack trace:
#0 /var/www/nextcloud/apps/files_notify_redis/lib/Notify/NotifyHandler.php(170): OCA\FilesNotifyRedis\Command\NotifyCommand->OCA\FilesNotifyRedis\Command\{closure}(Object(OCA\FilesNotifyRedis\Change\RenameChange))
#1 /var/www/nextcloud/apps/files_notify_redis/lib/Command/NotifyCommand.php(118): OCA\FilesNotifyRedis\Notify\NotifyHandler->listen(Object(Closure))
#2 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FilesNotifyRedis\Command\NotifyCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1000): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/nextcloud/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FilesNotifyRedis\Command\NotifyCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/nextcloud/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#9 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')

**Comment by icewind1991** [comment]
Should be fixed with daa2b315bc81f1d0d5e1400a6d40f5d44bdc0867
